This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Kovalenko_diploma.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Kovalenko_diploma.acn....done (46 entries accepted, 0 rejected).
Sorting entries....done (264 comparisons).
Generating output file Kovalenko_diploma.acr....done (56 lines written, 0 warnings).
Output written in Kovalenko_diploma.acr.
Transcript written in Kovalenko_diploma.alg.
